<a href="https://colab.research.google.com/github/Keshusrm/DeepLearning/blob/main/Lab1(Deep_Learning).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

import tensorflow as tf
import torch

print(tf.__version__)
print("GPU Available:", tf.config.list_physical_devices('GPU'))

a = torch.tensor((224,224))

print(a)
print(a.size())

2.20.0
GPU Available: []
tensor([224, 224])
torch.Size([2])


In [ ]:
m = torch.tensor([[1,2],
                  [3,4]])

print(m)
print(m.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [ ]:
t = torch.tensor([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
torch.zeros((3,4))

print(t.shape)

torch.Size([2, 2, 2])


In [ ]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.rand((3,3))

tensor([[0.2308, 0.3711, 0.6969],
        [0.0931, 0.8342, 0.7824],
        [0.9700, 0.1804, 0.6184]])

In [ ]:
A = torch.tensor([[1,2],
                  [3,4]])

B = torch.tensor([[5,6],
                  [7,8]])
print(A+B)
print(A**(1/2))
print(torch.sqrt(A))

tensor([[ 6,  8],
        [10, 12]])
tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])
tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


In [ ]:
torch.matmal(

In [ ]:
A=torch.rand((3,3))
B=torch.rand((3,3))
print(torch.matmul(A,B))
print(A)
print(torch.mean(A))
print(torch.min(A))
print(torch.sum(A), torch.max(A))
print(A[0,0])

tensor([[1.0545, 0.9748, 0.4562],
        [1.4504, 1.4114, 0.4605],
        [1.3067, 1.3836, 0.5499]])
tensor([[0.4849, 0.3110, 0.6688],
        [0.9382, 0.3689, 0.6678],
        [0.5543, 0.6178, 0.8016]])
tensor(0.6015)
tensor(0.3110)
tensor(5.4134) tensor(0.9382)
tensor(0.4849)
